### ISSUE TITLE
responsiveness compare

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#16]
wenn ich auf compare klicke, NICHT das Fenster nach unten verschieben.

**Comment by magnolo** [comment]
soll dass fenster so gross bleiben? oder soll es vollbild werden?

**Comment by WeFeelTheWorld** [comment]
würd auf hälfte gehen, so dass weiterhin die Karte klickbar. erste Zeile Sticky. scrollbar. choice der länder über die karte (touchevent) oder über den fähnchen-button.
