### ISSUE TITLE
BrowseFullList-UND-Verknüfung

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#28]
Browse Full List → Listenansicht nach Kategorien Filtern → multiple Auswahl sollte eine “OR” Verknüpfung sein, keine “AND” Verknüpfung.
(Wenn ich mehrere Kategorien auswähle, will ich nicht wissen, welche Indikatoren alle diese Kriterien erfüllen, sondern, welche MINDESTENS EINE erfüllen)

![browsefulllist-und-verknufung](https://cloud.githubusercontent.com/assets/20107924/16960303/299dfcd6-4de9-11e6-8a76-a8318cc77172.png)

**Comment by aldorado** [comment]
Filters in full list are already OR not AND
