### ISSUE TITLE
BrowseFullList-Search

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#29]
Browse Full List → Suchfunktion funktioniert nicht. Liste der angezeigten Indikatoren reagiert nicht auf Eingabe ins Suchfeld.

![browsefulllist-search](https://cloud.githubusercontent.com/assets/20107924/16960509/2063f976-4dea-11e6-9659-61c710956938.png)

**Comment by aldorado** [comment]
The md-virtual-repeat-container looses its height after being filtered and the filter has been set to empty again, possible solution -> give md-list-items a specific height or the whole container

**Comment by aldorado** [comment]
Fixed by giving the md-virtual-repeat-container a fixed height of 65vh, could maybe cause problems @ mobile or older browser
