### ISSUE TITLE
Front-end Dev wie Exporter

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#30]
Browse Full List → Klick auf Indikator, keine Anzeige auf der Map. ANzeige wie Exporteransicht.

![browsefulllist-mapanzeige](https://cloud.githubusercontent.com/assets/20107924/16960538/33df2b74-4dea-11e6-9b31-10b90fe4b414.png)

**Comment by aldorado** [comment]
Do you mean like **Data Editor -> Indicators -> click on individual indicator** just without the data editing features?

**Comment by georg23** [comment]
**Browse Full List -> Indices -> click on a group:** visualize a group of indicators just like the exporter does (navigation menu on the top left). So far, clicking on groups in **Browse Full List** results in nothingness.

**Comment by aldorado** [comment]
#37

**Comment by aldorado** [comment]
after clicking on indicator -> vector-overlay over map

nothingness after clicking on group is in issue #37 

![screen shot 2016-07-27 at 17 41 10](https://cloud.githubusercontent.com/assets/6803560/17181737/64408a00-5421-11e6-906c-b464b26f8a3c.png)
