### ISSUE TITLE
DataEditor-StylesSavings

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#34]
Data Editor → Styles → kein create Button (wie im Indikator/Style Reiter). Kein löschen etc. kein editing

![dataeditor-stylessavings](https://cloud.githubusercontent.com/assets/20107924/16960716/e8a756e4-4dea-11e6-9d42-db8afae74b18.png)

**Comment by aldorado** [comment]
Done, is on branch |-alsstage
