### ISSUE TITLE
Compare un-select funktioniert nicht richtig

### ISSUE THREAD

**Issue by kame16** [magnolo/23#4]
Land X auswählen - auf compare clicken - andere Länder hinzufügen und entfernen funktioniert.
Wenn man Länder hinzufügt und dann Land X aus dem Vergleich entfernt, hängt sich das System aber auf (Land X wird aus der Compare Liste nicht entfernt, weitere Länder können nicht mehr hinzugefügt oder entfernt werden).
Click auf Details oder History resettet das Problem.

**Comment by magnolo** [comment]
Ein neues update ist online. Das verhalten ist noch nicht ganz optimiert. Bitte überprüfen ob un-select Funktioniert.

**Comment by magnolo** [comment]
Ah... I see.. Es tritt ein Problem auf, wenn ich das Land, welches als Basis dient, abwählen versuche...

**Comment by Jihadnes** [comment]
die bubbles sollten am besten eine Minimumgröße haben, bei der man Sie noch erkennt...
