### ISSUE TITLE
BASF Colour Ramp

### ISSUE THREAD

**Issue by Riedler** [magnolo/23#45]
Die Farben sind für BASF.
Ich kann sie einbauen wenn die Colour Ramp funkt.
Und wir müssen für den BASF die Typo auf Helvetica Neue ändern!

![bildschirmfoto 2016-07-21 um 12 40 57](https://cloud.githubusercontent.com/assets/15873544/17020179/94f3fd84-4f40-11e6-8784-3a414b804676.png)

**Comment by magnolo** [comment]
Color Ramp is there, but for now there is no option for choosing individual languages
