### ISSUE TITLE
D3 topoJS wie bei KILN

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/23#49]
Weniger Anfragen, geringere Bandbreite

Code unter:

http://www.who.int/violence_injury_prevention/road_traffic/death-on-the-roads/en/

**Comment by magnolo** [comment]
we us the Protocolbuffer Binary Format, wich is much more compact than topojson. Our shape are also much more complex than on the link provided. So the vector tiles we are fetching are no traffic issue
