### ISSUE TITLE
Rang-Anzeige bei Subindizes stimmt nicht überein

### ISSUE THREAD

**Issue by georg-23** [magnolo/23#6]
Beispiel United Kingdom:
Wenn ich zB UK (auf EPI Ebene) auswähle, sehe ich in der Ranganzeige N°12, nebenbei in der kurzen Rangliste seh ich N°11 NLD, N°12 UK, N°13 DNK. Alles gut soweit.
Wenn ich jetzt auf eine Subebene wechsle, zB Water & Sanitation, dann passt die Ranganzeige (UK N°10) nicht mehr mit der kurzen Rangliste überein (N°9 TWN, N°10 SGP, N°11 QTR).
Soweit ich das sehe, passiert dieser missmatch auf allen Subebenen.

**Comment by magnolo** [comment]
Danke für den Hinweis. Der Fehler ist behoben und wird im nächsten release mit online gestellt. 

Das Problem lag daran, dass bei Indizes mehrere Länder die gleichen Werte habe und es bei der Sortierung ein wenig durcheinander gekommen ist. Die Sortierfunktionen wurden jetzt eine zusammengefasst. (Wertanzeige und MiniList-Offset)
